[book]
authors = ["Andy Newton"]
language = "en"
multilingual = false
src = "src"
title = "An Implementer's Guide to the Registration Data Access Protocol (RDAP)"

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.variables]
use_env = true

[preprocessor.variables.variables]
# apparently needed for some reason
other_variabled_not_in_env= "value"

[output]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
